---
title: "2021-10-12-2e55"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
```


# load data.json
```{r}
today = "2021-10-12"
cat("data on:", today, "\n")

tag = "2e55"

dat_tag = read.csv2(paste0("data/json/", today, "/", tag, ".csv"))
cat("tag", tag, "has", nrow(dat_tag), "position data.")
```


```{r}
plan <- read_excel("data/plan/Wall_lignes_firminy.xlsx")
plan = as.data.frame(plan)
plan$`Start X` <- as.numeric(plan$`Start X`)/100
plan$`Start Y` <- as.numeric(plan$`Start Y`)/100
plan$`End X` <- as.numeric(plan$`End X`)/100
plan$`End Y` <- as.numeric(plan$`End Y`)/100
colnames(plan) = c("Name", "Length", "Linetype Scale", "Angle", "Delta X",
                   "Delta Y", "Delta Z", "EndX", "EndY", "EndZ", 
                   "StartX", "StartY", "StartZ")
q <- ggplot(plan) + theme_bw() + 
  geom_segment(aes(x=StartX, y=StartY, xend=EndX, yend=EndY))
```


# hourly plot{.tabset .tabset-pills}
```{r results='asis'}
for (day in 12){
  for (hour in 0:23){
    cat("\n")
    cat("## ", hour, "\n")
    temp_tag = dat_tag %>%
      filter(d==day & H==hour)
    if (nrow(temp_tag)!=0){
      p <- q + 
        geom_point(data = temp_tag, aes(x=x, y=y), col = "red", size = 1) +
        coord_fixed(ratio = 1, xlim = c(-32,3), ylim = c(-65,3)) +
        labs(x = "", y = "", title = paste0(tag, "_2021_10_", day, "_", hour, "H"))
      print(p)
      # ggsave(paste0("figure/0da6_2021_09_", day, "_", hour, ".png"), width = 5, height = 9)
    }
    cat("\n")
  }
}
```


# data from Ludo
```{r}
json_data = fromJSON(file = paste0("data/json/", today, "/20211012_2e55.json"))
cat("Total collected positions: ", length(json_data), "\n")

tagId_seq = unlist(lapply(json_data, function(x){x["tag_id"][[1]]}))
tagId = unique(tagId_seq)
nb_tag = length(tagId)

cat(nb_tag, "Tags are: ", tagId, "\n")
table(tagId_seq)

dat <- data.frame(tag = unlist(lapply(json_data, function(x){x["tag_id"][[1]]})),
                  x = unlist(lapply(json_data, function(x){x["x"][[1]]})),
                  y = unlist(lapply(json_data, function(x){x["y"][[1]]})),
                  record_timestamp = unlist(lapply(json_data, function(x){x["record_timestamp"][[1]]})))

dat = dat[order(dat$record_timestamp),]
dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
dat$x = as.numeric(dat$x)
dat$y = as.numeric(dat$y)

dat = dat[dat$record_timestamp>=min(dat_tag$record_timestamp) & dat$record_timestamp<=max(dat_tag$record_timestamp),]

table_tag <- data.frame(tag = tag)
table_tag$first_record = NA
table_tag$last_record = NA
table_tag$number = NA
table_tag$number_NA = NA
table_tag$ratio_non_NA = NA

for (k in 1:1){
  temp = dat
  temp$diff_ts = c(0, temp$record_timestamp[-1]-temp$record_timestamp[-nrow(temp)])
  
  table_tag$first_record[k] = head(as.character(temp$date),1)
  table_tag$last_record[k] = tail(as.character(temp$date),1)
  table_tag$number[k] = nrow(temp)
  table_tag$number_NA[k] = sum(is.na(temp$x))
  table_tag$ratio_non_NA[k] = round(1-table_tag$number_NA[k]/table_tag$number[k],2)
}

kable(table_tag) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

list_tag <- split(dat, dat$tag)

list_tag = lapply(list_tag, function(x){cbind(x, data.frame(diff_ts = c(0, x$record_timestamp[-1]-x$record_timestamp[-nrow(x)])))})

nq = 10
table_diff_ts = matrix(NA, nrow = nb_tag, ncol = nq+1)
colnames(table_diff_ts) = paste0(c(0:10)/10*100, "%")
rownames(table_diff_ts) = tagId
for (k in 1:nb_tag){
  tag = tagId[k]
  table_diff_ts[k,] = round(quantile(list_tag[tag][[1]]$diff_ts[-1], c(0:10)/10), 3)
}

kable(table_diff_ts) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


## hourly plot{.tabset .tabset-pills}
```{r results='asis'}
for (day in 12){
  for (hour in 0:23){
    cat("\n")
    cat("### ", hour, "\n")
    temp_tag = dat %>%
      filter(d==day & H==hour)
    if (nrow(temp_tag)!=0){
      p <- q + 
        geom_point(data = temp_tag, aes(x=x, y=y), col = "red", size = 1) +
        coord_fixed(ratio = 1, xlim = c(-32,3), ylim = c(-65,3)) +
        labs(x = "", y = "", title = paste0(tag, "_2021_10_", day, "_", hour, "H"))
      print(p)
      # ggsave(paste0("figure/0da6_2021_09_", day, "_", hour, ".png"), width = 5, height = 9)
    }
    cat("\n")
  }
}
```


# double check 
```{r}
json_data1 = fromJSON(file = paste0("data/json/", today, "/position_2e55.json"))
cat("Total collected positions: ", length(json_data1), "\n")

tagId_seq1 = unlist(lapply(json_data1, function(x){x["tag_id"][[1]]}))
tagId1 = unique(tagId_seq1)
nb_tag1 = length(tagId1)

cat(nb_tag1, "Tags are: ", tagId1, "\n")
table(tagId_seq1)

dat1 <- data.frame(tag = unlist(lapply(json_data1, function(x){x["tag_id"][[1]]})),
                  x = unlist(lapply(json_data1, function(x){x["x"][[1]]})),
                  y = unlist(lapply(json_data1, function(x){x["y"][[1]]})),
                  record_timestamp = unlist(lapply(json_data1, function(x){x["record_timestamp"][[1]]})))

dat1 = dat1[order(dat1$record_timestamp),]
dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
dat$x = as.numeric(dat$x)
dat$y = as.numeric(dat$y)

dat = dat[dat$record_timestamp>=min(dat_tag$record_timestamp) & dat$record_timestamp<=max(dat_tag$record_timestamp),]

table_tag <- data.frame(tag = tag)
table_tag$first_record = NA
table_tag$last_record = NA
table_tag$number = NA
table_tag$number_NA = NA
table_tag$ratio_non_NA = NA

for (k in 1:1){
  temp = dat
  temp$diff_ts = c(0, temp$record_timestamp[-1]-temp$record_timestamp[-nrow(temp)])
  
  table_tag$first_record[k] = head(as.character(temp$date),1)
  table_tag$last_record[k] = tail(as.character(temp$date),1)
  table_tag$number[k] = nrow(temp)
  table_tag$number_NA[k] = sum(is.na(temp$x))
  table_tag$ratio_non_NA[k] = round(1-table_tag$number_NA[k]/table_tag$number[k],2)
}

kable(table_tag) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

list_tag <- split(dat, dat$tag)

list_tag = lapply(list_tag, function(x){cbind(x, data.frame(diff_ts = c(0, x$record_timestamp[-1]-x$record_timestamp[-nrow(x)])))})

nq = 10
table_diff_ts = matrix(NA, nrow = nb_tag, ncol = nq+1)
colnames(table_diff_ts) = paste0(c(0:10)/10*100, "%")
rownames(table_diff_ts) = tagId
for (k in 1:nb_tag){
  tag = tagId[k]
  table_diff_ts[k,] = round(quantile(list_tag[tag][[1]]$diff_ts[-1], c(0:10)/10), 3)
}

kable(table_diff_ts) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

```

