---
title: "2021-12-22"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
```


# load data.json
```{r}
today = "2021-12-22"
cat("data on:", today, "\n")

json_data = fromJSON(file = paste0("data/json/", today, "/position.json"))
cat("Total collected positions: ", length(json_data), "\n")

tagId_seq = unlist(lapply(json_data, function(x){x["tag_id"][[1]]}))
tagId = unique(tagId_seq)
nb_tag = length(tagId)

cat(nb_tag, "Tags are: ", tagId, "\n")
table(tagId_seq)
```


# general analysis
```{r}
dat <- data.frame(tag = unlist(lapply(json_data, function(x){x["tag_id"][[1]]})),
                  x = unlist(lapply(json_data, function(x){x["x"][[1]]})),
                  y = unlist(lapply(json_data, function(x){x["y"][[1]]})),
                  record_timestamp = unlist(lapply(json_data, function(x){x["record_timestamp"][[1]]})))
dat = dat[order(dat$record_timestamp),]
dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
dat$x = as.numeric(dat$x)
dat$y = as.numeric(dat$y)

names_tag <- read.table(file = "data/tag_names_20211124.txt", header = T, sep = "\t")
names_tag = names_tag[names_tag$id%in%tagId, ]

tagId = names_tag$id
nb_tag = length(tagId)

dat = dat[dat$tag%in%tagId,]
dat$label = factor(dat$tag, levels = names_tag$id, labels = names_tag$label)
dat$tagn = as.numeric(factor(dat$tag, levels = names_tag$id, labels = 1:nb_tag))

list_tag <- split(dat, dat$tag)
list_tag = lapply(list_tag, function(x){
  x$diff_ts = c(0, x$record_timestamp[-1]-x$record_timestamp[-nrow(x)])
  x = x[c(1,which(x$diff_ts>=0.1)),]
})
```


## quality of collecting data
### statistics of collecting data
```{r}
table_tag <- data.frame(tag = names_tag$id, label = names_tag$label)
table_tag$first_record = NA
table_tag$last_record = NA
table_tag$number = NA
table_tag$number_NA = NA
table_tag$ratio_non_NA = NA
# table_tag$freq_1Q = NA
# table_tag$freq_median = NA
# table_tag$freq_3Q = NA


for (k in 1:nb_tag){
  tag = table_tag$tag[k]
  temp = list_tag[tag][[1]]
  temp$diff_ts = c(0, temp$record_timestamp[-1]-temp$record_timestamp[-nrow(temp)])
  
  table_tag$first_record[k] = head(as.character(temp$date),1)
  table_tag$last_record[k] = tail(as.character(temp$date),1)
  table_tag$number[k] = nrow(temp)
  table_tag$number_NA[k] = sum(is.na(temp$x))
  table_tag$ratio_non_NA[k] = round(1-table_tag$number_NA[k]/table_tag$number[k],2)
  # table_tag$freq_1Q[k] = round(quantile(temp$diff_ts, 0.25), 3)
  # table_tag$freq_median[k] = round(quantile(temp$diff_ts, 0.5), 3)
  # table_tag$freq_3Q[k] = round(quantile(temp$diff_ts, 0.75), 3)
}

kable(table_tag) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


### frequncy check of collecting data 
```{r}
nq = 10
table_diff_ts = matrix(NA, nrow = nb_tag, ncol = nq+1)
colnames(table_diff_ts) = paste0(c(0:10)/10*100, "%")
rownames(table_diff_ts) = tagId
for (k in 1:nb_tag){
  tag = tagId[k]
  table_diff_ts[k,] = round(quantile(list_tag[tag][[1]]$diff_ts[-1], c(0:10)/10), 3)
}
table_diff_ts = cbind.data.frame(label = names_tag$label, table_diff_ts)

kable(table_diff_ts) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


### sensibility check of collecting data 
```{r}
nq = 10
table_sensibility = matrix(NA, nrow = nb_tag, ncol = nq+2)
colnames(table_sensibility) = c("number", paste0(c(0:10)/10*100, "%"))
rownames(table_sensibility) = tagId
for (k in 1:nb_tag){
  tag = tagId[k]
  dat_tag = list_tag[[k]]
  
  rows_sel = which(dat_tag$diff_ts>5)
  if (length(rows_sel)>=1){
    nr = c()
    nd = c()
    ns = c()
    for (i in 1:length(rows_sel)){
      ki = rows_sel[i]
      s = dat_tag[(ki-1):ki,c("x","y")]
      if (sum(is.na(s))==0){
        nr = c(nr, ki)
        ns = c(ns, dat_tag$diff_ts[ki])
        d = dist(s)/100
        nd = c(nd, d)
      }
    }
    table_sensibility[k,] = matrix(c(length(nd), round(quantile(nd, 0:10/10),3)), nrow = 1, ncol = nq+2)
  }else{
    table_sensibility[k,] = matrix(c(0, rep(NA, nq+1)), nrow = 1, ncol = nq+2)
  }
}
table_sensibility = cbind.data.frame(label = names_tag$label, table_sensibility)

kable(table_sensibility) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


### plot with NAs
```{r}
timestamp_breaks = as.numeric(as.POSIXct(paste0(today, " ", sprintf("%02d", 0:23), ":00:00 CEST"))) + 3600*7
p <- ggplot(dat) + theme_bw() + 
  geom_point(aes(x=record_timestamp, y=tagn, col=tagn), size=0.5) +
  scale_x_continuous(breaks = timestamp_breaks, labels = 0:23) +
  scale_y_continuous(breaks = 1:nb_tag, labels = names_tag$label) + 
  scale_color_gradientn(colours = hue_pal()(nb_tag)) + 
  coord_cartesian(xlim = c(timestamp_breaks[1], timestamp_breaks[23]+3600)) +
  theme(legend.position = "None") +
  labs(x = "hour", y = "", title = today)
print(p)
```


### plot without NAs
```{r}
x_na = which(is.na(dat$x))
y_na = which(is.na(dat$y))
cat("if x_na = y_na:", identical(x_na, y_na), "\n")
cat("number of NA positions:", length(x_na), "/", length(tagId_seq), "(=", 
    length(x_na)/length(tagId_seq)*100, "%)", "\n")
if (length(x_na)!=0){
  dat = dat[-x_na,]
}
```


```{r}
timestamp_breaks = as.numeric(as.POSIXct(paste0(today, " ", sprintf("%02d", 0:23), ":00:00 CEST"))) + 3600*7
p <- ggplot(dat) + theme_bw() + 
  geom_point(aes(x=record_timestamp, y=tagn, col=tagn), size=0.5) +
  scale_x_continuous(breaks = timestamp_breaks, labels = 0:23) +
  scale_y_continuous(breaks = 1:nb_tag, labels = names_tag$label) + 
  scale_color_gradientn(colours = hue_pal()(nb_tag)) + 
  coord_cartesian(xlim = c(timestamp_breaks[1], timestamp_breaks[23]+3600)) +
  theme(legend.position = "None") +
  labs(x = "hour", y = "", title = today)
print(p)
```


```{r}
list_tag <- split(dat, dat$tag)

for (tag in names(list_tag)){
  if (!is.null(list_tag[tag][[1]])){
    dd = list_tag[tag][[1]]
    dd[,c("x","y")] = dd[,c("x","y")]/100
    rownames(dd) = 1:nrow(dd)
    dd$num = 1:nrow(dd)
    dd$timediff = c(0, dd$record_timestamp[-1] - dd$record_timestamp[-nrow(dd)])
    
    list_tag[tag][[1]] = dd
  }
}
dat = do.call(rbind.data.frame, list_tag)
```


# plot {.tabset .tabset-pills}
```{r}
load("data/plan/plan_firminy.RData")
```


```{r results='asis'}
for (k in 1:nb_tag){
  tag = names_tag$id[k]
  label = names_tag$label[k]
  cat("\n")
  cat("## ", label, "\n")
  dd = list_tag[tag][[1]]
  if (!is.null(dd)){
    q <- p + 
      geom_point(data = dd, aes(x=x,y=y), col="red", size = 1) +
      coord_equal(ratio = 1, xlim = c(-20,20), ylim = c(-30,30)) + 
      labs(x = "", y = "", title = paste0(tag, " - ", names_tag$Matériel[names_tag$id==tag]))
    print(q)
  }else{
    cat("NO DATA for plot!!")
  }
  cat("\n")
}
```


# plot by hour {.tabset .tabset-pills}
```{r results='asis'}
names_tag_all <- read.table(file = "data/tag_names_20211124.txt", header = T, sep = "\t")
nb_tag_all = nrow(names_tag_all)

date_sel = rev(as.Date(0:(-8), origin = today))

temp1 = read.csv2(paste0("data/json/", date_sel[1], "/position.csv"))
temp1 = temp1 %>% filter(tag %in% names_tag_all$id)
temp2 = read.csv2(paste0("data/json/", date_sel[2], "/position.csv"))
temp2 = temp2 %>% filter(tag %in% names_tag_all$id)
temp3 = read.csv2(paste0("data/json/", date_sel[3], "/position.csv"))
temp3 = temp3 %>% filter(tag %in% names_tag_all$id)
temp4 = read.csv2(paste0("data/json/", date_sel[4], "/position.csv"))
temp4 = temp4 %>% filter(tag %in% names_tag_all$id)
temp5 = read.csv2(paste0("data/json/", date_sel[5], "/position.csv"))
temp5 = temp5 %>% filter(tag %in% names_tag_all$id)
temp6 = read.csv2(paste0("data/json/", date_sel[6], "/position.csv"))
temp6 = temp6 %>% filter(tag %in% names_tag_all$id)
temp7 = read.csv2(paste0("data/json/", date_sel[7], "/position.csv"))
temp7 = temp7 %>% filter(tag %in% names_tag_all$id)
temp8 = read.csv2(paste0("data/json/", date_sel[8], "/position.csv"))
temp8 = temp8 %>% filter(tag %in% names_tag_all$id)
temp9 = read.csv2(paste0("data/json/", date_sel[9], "/position.csv"))
temp9 = temp9 %>% filter(tag %in% names_tag_all$id)

temp_tag = do.call(rbind.data.frame, list(temp1,temp2,temp3,temp4,temp5,temp6,temp7,temp8,temp9))
temp_tag$date = as.Date(temp_tag$date, format = "%Y-%m-%d")

for (k in 1:nb_tag_all){
  tag = names_tag_all$id[k]
  label = names_tag_all$label[k]
  cat("\n")
  cat("## ", label, " {.tabset .tabset-pills}", "\n")
  for (hour in sprintf("%02d", 0:23)){
    cat("\n")
    cat("### ", hour, "\n")
    temp_tag_hour = temp_tag[temp_tag$tag==tag,] %>%
      filter(H==as.numeric(hour))
    if (nrow(temp_tag_hour)!=0){
      q <- p + 
        geom_point(data = temp_tag_hour, aes(x=x, y=y), col = "red", size = 0.5) +
        coord_equal(ratio = 1, xlim = c(-20,20), ylim = c(-30,30)) + 
        facet_wrap(~date, ncol = 3) +
        labs(x = "", y = "")
      print(q)
      # ggsave(paste0("figure/0da6_2021_09_", day, "_", hour, ".png"), width = 5, height = 9)
    }
    cat("\n")
  }
  cat("\n")
}
```

