---
title: "2021-10-19-Test"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
load("data/plan/plan_firminy.RData")
```


# load data
```{r}
data = read.csv2("data/json/2021-10-19/0daa.csv")
tag = "0daa"

coord1 = as.data.frame(matrix(c(-7.811,-8.616,
                                -5.811,-8.616,
                                -3.811,-8.616,
                                -1.811,-8.616,
                                 0.189,-8.616,
                                 2.189,-8.616), ncol = 2, byrow = T))
colnames(coord1) = c("x", "y")

coord2 = as.data.frame(matrix(c(-8.752,8.694,
                                -6.752,8.694,
                                -4.752,8.694,
                                -2.752,8.694,
                                -0.752,8.694,
                                 1.248,8.694), ncol = 2, byrow = T))
colnames(coord2) = c("x", "y")
```

# test 1
## contre le corps
```{r}
dat = data %>%
  filter(H==11 & M>=28 & M<=30)
dat$num = 1:nrow(dat)

# q <- p + 
#   geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
#   geom_point(data = coord1, aes(x=x,y=y), col = "black", size=1) +
#   coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
#   labs(x="", y="", title = "0daa: 11H28 - 11H30")
# print(q)

steps = dat$num
q <- p + 
  geom_point(data = dat, aes(x=x, y=y), col="red", size=0.5) + 
  geom_point(data = coord1, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 11H28 - 11H30")
print(q)
q <- q + transition_time(num) + labs(title = paste0("0daa: 11H28 - 11H30 ", "{frame_time}/", length(steps)))
# steps = 1:5
animate(q, nframes = max(steps)-min(steps)+1, fps = 5, renderer = gifski_renderer(loop = T), 
        width = 1500, height = 1000, res = 150)
```

## dans le poche
```{r}
dat = data %>%
  filter(H==11 & M>=35 & M<=37)

q <- p + 
  geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
  geom_point(data = coord1, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 11H35 - 11H37")
print(q)
```

## dessus de la tête
```{r}
dat = data %>%
  filter(H==11 & M>=38 & M<=40)

q <- p + 
  geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
  geom_point(data = coord1, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 11H38 - 11H40")
print(q)
```



# test 2
## contre le corps
```{r}
dat = data %>%
  filter(H==11 & M>=56 & M<=59)

q <- p + 
  geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
  geom_point(data = coord2, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 11H56 - 11H59")
print(q)
```

## dans le poche
```{r}
dat = data %>%
  filter(H==12 & M>=00 & M<=03)

q <- p + 
  geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
  geom_point(data = coord2, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 12H00 - 12H03")
print(q)
```

## dessus de la tête
```{r}
dat = data %>%
  filter(H==12 & M>=04 & M<=07)

q <- p + 
  geom_point(data = dat, aes(x=x,y=y), col = "red", size=0.5) +
  geom_point(data = coord2, aes(x=x,y=y), col = "black", size=1) +
  coord_fixed(ratio = 1, xlim = c(-20,20), ylim = c(-15,10)) + 
  labs(x="", y="", title = "0daa: 12H04 - 12H07")
print(q)
```

