---
title: "analysis - tags soignants"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
load("data/plan/plan_firminy.RData")
```


# load data.json
```{r}
tagId = c("cf31", "8718", "58b2")
nb_tag = length(tagId)

list_tag <- vector("list", nb_tag)
names(list_tag) = tagId
for (k in 1:nb_tag){
  temp_tag = fromJSON(file = paste0("data/json/tag/", tagId[k], "/position.json"))
  dat <- data.frame(tag = unlist(lapply(temp_tag, function(x){x["tag_id"][[1]]})),
                    x = unlist(lapply(temp_tag, function(x){x["x"][[1]]})),
                    y = unlist(lapply(temp_tag, function(x){x["y"][[1]]})),
                    record_timestamp = unlist(lapply(temp_tag,function(x){x["record_timestamp"][[1]]})))
  dat = dat[order(dat$record_timestamp),]
  dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
  dat$x = as.numeric(dat$x)/100
  dat$y = as.numeric(dat$y)/100
  list_tag[[k]] = dat
}
```


# general analysis
## quality of collecting data
```{r}
table_tag <- data.frame(tag = tagId)
table_tag$first_record = NA
table_tag$last_record = NA
table_tag$number = NA
table_tag$number_NA = NA
table_tag$ratio_non_NA = NA
# table_tag$freq_1Q = NA
# table_tag$freq_median = NA
# table_tag$freq_3Q = NA


for (k in 1:nb_tag){
  tag = table_tag$tag[k]
  temp = list_tag[tag][[1]]
  temp$diff_ts = c(0, temp$record_timestamp[-1]-temp$record_timestamp[-nrow(temp)])
  
  table_tag$first_record[k] = head(as.character(temp$date),1)
  table_tag$last_record[k] = tail(as.character(temp$date),1)
  table_tag$number[k] = nrow(temp)
  table_tag$number_NA[k] = sum(is.na(temp$x))
  table_tag$ratio_non_NA[k] = round(1-table_tag$number_NA[k]/table_tag$number[k],2)
  # table_tag$freq_1Q[k] = round(quantile(temp$diff_ts, 0.25), 3)
  # table_tag$freq_median[k] = round(quantile(temp$diff_ts, 0.5), 3)
  # table_tag$freq_3Q[k] = round(quantile(temp$diff_ts, 0.75), 3)
}

kable(table_tag) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


```{r}
list_tag = lapply(list_tag, function(x){cbind(x, data.frame(diff_ts = c(0, x$record_timestamp[-1]-x$record_timestamp[-nrow(x)])))})

nq = 10
table_diff_ts = matrix(NA, nrow = nb_tag, ncol = nq+1)
colnames(table_diff_ts) = paste0(c(0:10)/10*100, "%")
rownames(table_diff_ts) = tagId
for (k in 1:nb_tag){
  tag = tagId[k]
  table_diff_ts[k,] = round(quantile(list_tag[tag][[1]]$diff_ts[-1], c(0:10)/10), 3)
}

kable(table_diff_ts) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```


# analysis by tag{.tabset .tabset-pills}
## `r tagId[1]` {.tabset .tabset-pills}
```{r}
tag = tagId[1]
dat_tag = list_tag[tag][[1]]
rownames(dat_tag) = 1:nrow(dat_tag)

rows_sel = which(dat_tag$diff_ts>10)[-1]
dat_tag_sel = dat_tag[unique(c(rows_sel-1, rows_sel, rows_sel+1)),]
dat_tag_sel = dat_tag_sel[order(dat_tag_sel$record_timestamp),]

list_tagr = vector("list", length(rows_sel))
for (k in 1:length(rows_sel)){
  r = rows_sel[k]

  r1 = tail(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))<r),1)
  r2 = head(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))>r),1)

  list_tagr[[k]] = dat_tag[(r1-2):(r2+2),c("tag","x","y","record_timestamp","diff_ts")]
}
nr1 = which(unlist(lapply(list_tagr, nrow))==7)
nr2 = which(unlist(lapply(list_tagr, function(x){sum(is.na(x))==0})))
nr = intersect(nr1, nr2)

cat(length(nr), "situations to be investigated for the tag", tag, "\n")

list_tagr_sel = list_tagr[nr]
dist1 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[3,4]}))
dist2 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[4,5]}))

nq = 10
table_quantile1 = matrix(round(quantile(dist1, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile1) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the last point before the stop and the first point after the stop", "\n")
kable(table_quantile1) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

table_quantile1 = rbind(table_quantile1, NA)
for (i in 1:ncol(table_quantile1)){
  table_quantile1[2,i] = which.min(abs(dist1 - as.numeric(table_quantile1[1,i])))
}

nq = 10
table_quantile2 = matrix(round(quantile(dist2, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile2) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the first two points after the stop", "\n")
kable(table_quantile2) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```

```{r results='asis'}
for (k in 1:ncol(table_quantile1)){
  cat("\n")
  cat("### ", colnames(table_quantile1)[k], "\n")
  j = table_quantile1[2,k]
  tagr = list_tagr[[nr[j]]]

  kable(tagr) %>%
    kable_styling(bootstrap_options = "striped", full_width = T)

  q <- p + 
    geom_point(data = tagr[1:3,], aes(x=x,y=y, col = "1-before"), size = 0.5) + 
    geom_point(data = tagr[5:7,], aes(x=x,y=y, col = "3-after"), size = 0.5) +
    geom_point(data = tagr[4,], aes(x=x,y=y, col = "2-start"), size = 0.5) + 
    coord_fixed(ratio=1, xlim = c((min(tagr$x)-1),(max(tagr$x)+1)), ylim = c((min(tagr$y)-1),(max(tagr$y)+1))) +
    theme(legend.title = element_blank()) +
    labs(x="", y="")
  print(q)
  cat("\n")
}
```


## `r tagId[2]` {.tabset .tabset-pills}
```{r}
tag = tagId[2]
dat_tag = list_tag[tag][[1]]
rownames(dat_tag) = 1:nrow(dat_tag)

rows_sel = which(dat_tag$diff_ts>10)[-1]
dat_tag_sel = dat_tag[unique(c(rows_sel-1, rows_sel, rows_sel+1)),]
dat_tag_sel = dat_tag_sel[order(dat_tag_sel$record_timestamp),]

list_tagr = vector("list", length(rows_sel))
for (k in 1:length(rows_sel)){
  r = rows_sel[k]

  r1 = tail(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))<r),1)
  r2 = head(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))>r),1)

  list_tagr[[k]] = dat_tag[(r1-2):(r2+2),c("tag","x","y","record_timestamp","diff_ts")]
}
nr1 = which(unlist(lapply(list_tagr, nrow))==7)
nr2 = which(unlist(lapply(list_tagr, function(x){sum(is.na(x))==0})))
nr = intersect(nr1, nr2)

cat(length(nr), "situations to be investigated for the tag", tag, "\n")

list_tagr_sel = list_tagr[nr]
dist1 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[3,4]}))
dist2 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[4,5]}))

nq = 10
table_quantile1 = matrix(round(quantile(dist1, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile1) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the last point before the stop and the first point after the stop", "\n")
kable(table_quantile1) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

table_quantile1 = rbind(table_quantile1, NA)
for (i in 1:ncol(table_quantile1)){
  table_quantile1[2,i] = which.min(abs(dist1 - as.numeric(table_quantile1[1,i])))
}

nq = 10
table_quantile2 = matrix(round(quantile(dist2, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile2) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the first two points after the stop", "\n")
kable(table_quantile2) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```

```{r results='asis'}
for (k in 1:ncol(table_quantile1)){
  cat("\n")
  cat("### ", colnames(table_quantile1)[k], "\n")
  j = table_quantile1[2,k]
  tagr = list_tagr[[nr[j]]]

  kable(tagr) %>%
    kable_styling(bootstrap_options = "striped", full_width = T)

  q <- p + 
    geom_point(data = tagr[1:3,], aes(x=x,y=y, col = "1-before"), size = 0.5) + 
    geom_point(data = tagr[5:7,], aes(x=x,y=y, col = "3-after"), size = 0.5) +
    geom_point(data = tagr[4,], aes(x=x,y=y, col = "2-start"), size = 0.5) + 
    coord_fixed(ratio=1, xlim = c((min(tagr$x)-1),(max(tagr$x)+1)), ylim = c((min(tagr$y)-1),(max(tagr$y)+1))) +
    theme(legend.title = element_blank()) +
    labs(x="", y="")
  print(q)
  cat("\n")
}
```


## `r tagId[3]` {.tabset .tabset-pills}
```{r}
tag = tagId[3]
dat_tag = list_tag[tag][[1]]
rownames(dat_tag) = 1:nrow(dat_tag)

rows_sel = which(dat_tag$diff_ts>10)[-1]
dat_tag_sel = dat_tag[unique(c(rows_sel-1, rows_sel, rows_sel+1)),]
dat_tag_sel = dat_tag_sel[order(dat_tag_sel$record_timestamp),]

list_tagr = vector("list", length(rows_sel))
for (k in 1:length(rows_sel)){
  r = rows_sel[k]

  r1 = tail(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))<r),1)
  r2 = head(which(!is.na(dat_tag$x) & as.numeric(rownames(dat_tag))>r),1)

  list_tagr[[k]] = dat_tag[(r1-2):(r2+2),c("tag","x","y","record_timestamp","diff_ts")]
}
nr1 = which(unlist(lapply(list_tagr, nrow))==7)
nr2 = which(unlist(lapply(list_tagr, function(x){sum(is.na(x))==0})))
nr = intersect(nr1, nr2)

cat(length(nr), "situations to be investigated for the tag", tag, "\n")

list_tagr_sel = list_tagr[nr]
dist1 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[3,4]}))
dist2 = unlist(lapply(list_tagr_sel, function(x){as.matrix(dist(x[,c("x","y")]))[4,5]}))

nq = 10
table_quantile1 = matrix(round(quantile(dist1, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile1) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the last point before the stop and the first point after the stop", "\n")
kable(table_quantile1) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)

table_quantile1 = rbind(table_quantile1, NA)
for (i in 1:ncol(table_quantile1)){
  table_quantile1[2,i] = which.min(abs(dist1 - as.numeric(table_quantile1[1,i])))
}

nq = 10
table_quantile2 = matrix(round(quantile(dist2, 0:10/10),3), nrow = 1, ncol = nq+1)
colnames(table_quantile2) = paste0(c(0:10)/10*100, "%")
cat("quantile of distances between the first two points after the stop", "\n")
kable(table_quantile2) %>%
  kable_styling(bootstrap_options = "striped", full_width = T)
```

```{r results='asis'}
for (k in 1:ncol(table_quantile1)){
  cat("\n")
  cat("### ", colnames(table_quantile1)[k], "\n")
  j = table_quantile1[2,k]
  tagr = list_tagr[[nr[j]]]

  kable(tagr) %>%
    kable_styling(bootstrap_options = "striped", full_width = T)

  q <- p + 
    geom_point(data = tagr[1:3,], aes(x=x,y=y, col = "1-before"), size = 0.5) + 
    geom_point(data = tagr[5:7,], aes(x=x,y=y, col = "3-after"), size = 0.5) +
    geom_point(data = tagr[4,], aes(x=x,y=y, col = "2-start"), size = 0.5) + 
    coord_fixed(ratio=1, xlim = c((min(tagr$x)-1),(max(tagr$x)+1)), ylim = c((min(tagr$y)-1),(max(tagr$y)+1))) +
    theme(legend.title = element_blank()) +
    labs(x="", y="")
  print(q)
  cat("\n")
}
```

