---
title: "analysis-4596-20220211"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
load("data/plan/plan_firminy.RData")
```


# load data.json
```{r}
today = "2022-02-11"
data = read.csv2("data/json/2022-02-11/4596.csv")

p + theme_bw() + 
  geom_point(data = data, aes(x=x,y=y), col="red", size=0.5) +
  coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
  labs(x="", y="", title = paste0("tag 4596 - ", today))
```


```{r eval=FALSE, include=FALSE}
### plot to recognize the trajectories
for (k in 1001:8377){
  p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", title = paste0(data$date[k]," - ",k))
  ggsave(paste0("figure/2022-02-11/4596/",k,".png"), width = 7, height=11)
}

# stop
k = 276:602
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))

# stop
k = 779:978
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))

# stop
k = 1072:1309
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))

# stop
k = 1500:1523
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))


k = 1524:2680
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))


k = 2681:2730
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))


k = 2731:8377
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```


# tests {.tabset .tabset-pills}
## test1 - badge a bout de bras{.tabset .tabset-pills}
### aller
```{r}
k = 100:188
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```

### retour
```{r}
k = 189:275
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```


## test2 - badge dans la poche contre le coeur {.tabset .tabset-pills}
### aller
```{r}
k = 603:693
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```

### retour
```{r}
k = 694:778
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```


## test3 - en courant {.tabset .tabset-pills}
### aller
```{r}
k = 979:1018
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```

### retour
```{r}
k = 1019:1072
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```


## test4 - dans la poche comme d'habitude {.tabset .tabset-pills}
### aller
```{r}
k = 1310:1405
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```

### retour
```{r}
k = 1406:1499
p + theme_bw() + 
    geom_point(data = data[k,], aes(x=x,y=y), col="red") +
    coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
    labs(x="", y="", 
         title = paste0(data$date[k[1]]," - ",k[1]),
         subtitle = paste0(data$date[k[length(k)]]," - ",k[length(k)]))
```


# analysis
```{r}
output = data.frame(matrix(NA, nrow = 8, ncol = 3))
colnames(output) = c("test", "num_start", "num_end")

output[1,] = c("test1_aller",100,188)
output[2,] = c("test1_retour",189,275)
output[3,] = c("test2_aller",603,693)
output[4,] = c("test2_retour",694,778)
output[5,] = c("test3_aller",979,1018)
output[6,] = c("test3_retour",1019,1072)
output[7,] = c("test4_aller",1310,1405)
output[8,] = c("test5_retour",1406,1499)

output$time_start = data$date[as.numeric(output$num_start)]
output$time_end = data$date[as.numeric(output$num_end)]

output$dwell = NA
output$count = NA
output$na = NA
output$freq_min = NA
output$freq_max = NA
output$dist = NA
output$speed = NA 
for (k in 1:8){
  na = as.numeric(output$num_start[k])
  nb = as.numeric(output$num_end[k])
  output$dwell[k] = round(data$record_timestamp[nb]-data$record_timestamp[na],3)
  output$count[k] = nb-na+1
  output$na[k] = sum(is.na(data$x[na:nb]))
  output$freq_min[k] = round(min(data$timediff[na:nb]),3)
  output$freq_max[k] = round(max(data$timediff[na:nb]),3)
  output$dist[k] = round(dist(data[c(na,nb), c("x","y")]),3)
  output$speed[k] = round(output$dist[k]/output$dwell[k],3)
}

datatable(output, filter = "top", options = list(pageLength = nrow(output)))
```

