---
title: "Antoine 2022.03.05"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
source("code/fun_convert_date.R")

names_tag <- read.xlsx("data/Inventaire Tags - Firminy - 2022.xlsx")

load("data/plan/plan_firminy.RData")
```


# 2022-03-05
```{r}
json_data = fromJSON(file = paste0("data/json/2022-03-05/position.json"))

dat <- data.frame(tag = unlist(lapply(json_data, function(x){x["tag_id"][[1]]})),
                  x = unlist(lapply(json_data, function(x){x["x"][[1]]})),
                  y = unlist(lapply(json_data, function(x){x["y"][[1]]})),
                  record_timestamp = unlist(lapply(json_data, function(x){x["record_timestamp"][[1]]})))
dat = dat %>% filter(tag %in% c("4288","295e"))
dat = dat[order(dat$record_timestamp),]
dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
dat$date = as.character(dat$date)
dat$x = as.numeric(dat$x)
dat$y = as.numeric(dat$y)

list_tag <- split(dat, dat$tag)

data1 = list_tag[[1]]
data1$diff_ts = round(c(0, data1$record_timestamp[-1]-data1$record_timestamp[-nrow(data1)]), 3)
data1$x = data1$x/100
data1$y = data1$y/100
data1$diff_dist = NA
for (k in 2:nrow(data1)){
  data1$diff_dist[k] = as.numeric(dist(data1[(k-1):k,c("x","y")]))
}

data2 = list_tag[[2]]
data2$diff_ts = round(c(0, data2$record_timestamp[-1]-data2$record_timestamp[-nrow(data2)]), 3)
data2$x = data2$x/100
data2$y = data2$y/100
data2$diff_dist = NA
for (k in 2:nrow(data2)){
  data2$diff_dist[k] = as.numeric(dist(data2[(k-1):k,c("x","y")]))
}

data = rbind.data.frame(data1, data2)
```


## tag 295e - Testeur
```{r warning=FALSE}
datatable(data1)
```


## tag 4288 - Antoine
```{r warning=FALSE}
datatable(data2)
```


# general analysis
```{r}
output_table = data.frame(tag = unique(data$tag))
output_table$count = c(nrow(data1), nrow(data2))
output_table$count_NA = c(sum(is.na(data1$x)), sum(is.na(data2$x)))
output_table$NA_ratio = round(output_table$count_NA/output_table$count,2)
output_table$time_start = c(as.character(head(data1$date,1)), as.character(head(data2$date,1)))
output_table$time_end = c(as.character(tail(data1$date,1)), as.character(tail(data2$date,1)))

datatable(output_table)
```


# hourly plot {.tabset .tabset-pills}
```{r results='asis', fig.height=20, fig.width=18}
tags = unique(data$tag)
tags = names_tag %>% filter(Identifiant %in% tags)

data$H = factor(as.numeric(data$H), levels = c(0:23))

q = p + theme_bw() +
  geom_point(data = data, aes(x=x, y=y, col=tag), na.rm = T) +
  coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
  labs(x = "", y = "") + 
  facet_wrap(~H, nrow = 4, drop = F)
print(q)
# ggsave(filename = "fig/20220217_Antoine_hourly_plot.png", width=18, height=18)
```


# discontinued situations {.tabset .tabset-pills}
```{r}
data2 = data2 %>%
  filter(record_timestamp <= max(data1$record_timestamp)) %>%
  filter(record_timestamp >= min(data1$record_timestamp))

nt = sum(data2$diff_dist>=5, na.rm = T)
```


```{r results='asis'}
for (k in 1:nt){
  cat("\n")
  cat("## ", "case", k, "\n")
  t2 = order(data2$diff_dist, decreasing = T)[k]
  dat2 = data2[(t2-1):(t2+1),]
  datatable(dat2)
  
  dat1 = data1 %>%
    filter(record_timestamp>=min(dat2$record_timestamp)) %>%
    filter(record_timestamp<=max(dat2$record_timestamp))
  
  if (nrow(dat1)==0){
    cat("no data for Testeur!!!", "\n")
  }else{
    p + theme_bw() +
      geom_point(data = dat1, aes(x=x, y=y, col="Testeur"), na.rm = T) +
      geom_point(data = dat2, aes(x=x, y=y, col="Antoine"), na.rm = T) +
      scale_color_manual(values = c("blue", "red")) +
      coord_equal(ratio = 1, xlim = c(-20,17), ylim = c(-35,35)) +
      theme(legend.title = element_blank()) +
      labs(x = "", y = "", title = dat2$date[1], subtitle = dat2$date[3])
  }
  cat("\n")
}
```
