---
title: "first-analysis"
author: "cfcforever"
date: "2021-09-26"
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
library(ggplot2)
library(gganimate)
library(cowplot)
library(rjson)
library(kableExtra)
library(nnet)
library(dplyr)
library(lubridate)

source("code/fun_convert_date.R")
```


# load data.json
```{r}
today = "2021-09-25"
cat("data on:", today, "\n")

json_data = fromJSON(file = paste0("data/json/", today, "/position.json"))
cat("Total collected positions: ", length(json_data), "\n")

tagId_seq = unlist(lapply(json_data, function(x){x["tag_id"][[1]]}))
tagId = unique(tagId_seq)
nb_tag = length(tagId)

cat("Tags are: ", tagId, "\n")
table(tagId_seq)
```


## general analysis
```{r}
dat <- data.frame(tag = unlist(lapply(json_data, function(x){x["tag_id"][[1]]})),
                  x = unlist(lapply(json_data, function(x){x["x"][[1]]})),
                  y = unlist(lapply(json_data, function(x){x["y"][[1]]})),
                  record_timestamp = unlist(lapply(json_data, function(x){x["record_timestamp"][[1]]})))
dat = dat[order(dat$record_timestamp),]
dat = cbind.data.frame(dat, convert_date(dat$record_timestamp))
dat$x = as.numeric(dat$x)
dat$y = as.numeric(dat$y)

list_tag <- split(dat, dat$tag)
```


### quality of collecting data
```{r}
table_tag <- data.frame(tag = tagId)
table_tag$first_record = NA
table_tag$last_record = NA
table_tag$number = NA
table_tag$number_NA = NA
table_tag$ratio_non_NA = NA
table_tag$freq_1Q = NA
table_tag$freq_median = NA
table_tag$freq_3Q = NA


for (k in 1:nb_tag){
  tag = table_tag$tag[k]
  temp = list_tag[tag][[1]]
  temp$diff_ts = c(0, temp$record_timestamp[-1]-temp$record_timestamp[-nrow(temp)])
  
  table_tag$first_record[k] = head(as.character(temp$date),1)
  table_tag$last_record[k] = tail(as.character(temp$date),1)
  table_tag$number[k] = nrow(temp)
  table_tag$number_NA[k] = sum(is.na(temp$x))
  table_tag$ratio_non_NA[k] = round(1-table_tag$number_NA[k]/table_tag$number[k],2)
  table_tag$freq_1Q[k] = round(quantile(temp$diff_ts, 0.25), 3)
  table_tag$freq_median[k] = round(quantile(temp$diff_ts, 0.5), 3)
  table_tag$freq_3Q[k] = round(quantile(temp$diff_ts, 0.75), 3)
}

kable(table_tag) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)

x_na = which(is.na(dat$x))
y_na = which(is.na(dat$y))
cat("if x_na = y_na:", identical(x_na, y_na), "\n")
cat("number of invalid positions:", length(x_na), "/", length(tagId_seq), "(=", 
    length(x_na)/length(tagId_seq)*100, "%)", "\n")
if (length(x_na)!=0){
  dat = dat[-x_na,]
}
```


```{r}
list_tag <- split(dat, dat$tag)

for (tag in names(list_tag)){
  if (!is.null(list_tag[tag][[1]])){
    dd = list_tag[tag][[1]]
    dd[,c("x","y")] = dd[,c("x","y")]/100
    rownames(dd) = 1:nrow(dd)
    dd$num = 1:nrow(dd)
    dd$timediff = c(0, dd$record_timestamp[-1] - dd$record_timestamp[-nrow(dd)])
    
    list_tag[tag][[1]] = dd
  }
}

dat = do.call(rbind.data.frame, list_tag)
```


# plot 
```{r}
for (tag in names(list_tag)){
  dd = list_tag[tag][[1]]
  
  p <- ggplot(dd) + theme_bw() +
    geom_point(aes(x=x,y=y)) +
    coord_equal(ratio = 1, xlim = c(-30,5), ylim = c(-60,5)) +
    labs(title = tag)
  print(p)
}
```


