---
title: "Summary report since 2021-12-22"
# author: "cfcforever"
# date: ""
output: 
  workflowr::wflow_html:
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
source("code/packages_and_functions.R")
day0 = "2021-12-22"
today = "2022-05-23"
cat("data on:", today, "\n")
```


```{r eval=FALSE, include=FALSE}
today = "2022-01-17"
days = seq(as.Date("2021-12-22"),to=as.Date(today),by='1 day')

list_output = vector("list", length(days))
names(list_output) = days
for (k in 1:length(days)){
  day = days[k]
  data = read.csv2(paste0("data/json/", day, "/position.csv"))
  list_tag <- split(data, data$tag)
  output = data.frame(tag = names(list_tag))
  output$number = lapply(list_tag, nrow)
  output$date = day
  list_output[[k]] = output
  print(day)
}
save(list_output, file = "output/list_output.RData")
```


# general presentation
```{r}
load("output/list_output.RData")
if (!any(names(list_output)==today)){
  data = read.csv2(paste0("data/json/", today, "/position.csv"))
  list_tag <- split(data, data$tag)
  output = data.frame(tag = names(list_tag))
  output$number = lapply(list_tag, nrow)
  output$date = today
  list_output[[today]] = output
  save(list_output, file = "output/list_output.RData")
}
output = do.call(rbind.data.frame, list_output)

tagId = unique(output$tag)
names_tag = read.xlsx("data/Inventaire Tags - Firminy - 2022.xlsx")
names_tag = names_tag %>% filter(Identifiant %in% tagId)
names_tag = names_tag[order(match(names_tag$Identifiant, tagId)), ]

days = unique(output$date)

table = as.data.frame(matrix(NA, nrow = length(tagId), ncol = length(days)))
colnames(table) = days
rownames(table) = tagId
for (i in 1:nrow(output)){
  table[which(tagId==output$tag[i]), which(days==output$date[i])] = output$number[i]
}
table = cbind(data.frame(type = names_tag$affectation), table)

table = table[,c(1,ncol(table):2)]
datatable(table, editable = F, extensions = 'Buttons', options = list(pageLength = nrow(table), dom = 'Bfrtip'))
```



# general statistics

## daily statistics
```{r}
table_general = data.frame(date = days)
table_general$number_tag = as.numeric(lapply(list_output, function(x){nrow(x)}))
table_general$number_data = as.numeric(lapply(list_output, function(x){sum(as.numeric(x$number))}))

table_general = table_general[nrow(table_general):1,]

datatable(table_general, editable = F, extensions = 'Buttons', options = list(pageLength = 20, dom = 'Bfrtip'))
```


## tag statistics
```{r}
tag_general = data.frame(id = names_tag$Identifiant, label = names_tag$affectation)
tag_general$number_days = NA
tag_general$number_data = NA
tag_general$daily_average = NA
for (k in 1:nrow(tag_general)){
  tag_general$number_days[k] = sum(output$tag == tag_general$id[k])
  tag_general$number_data[k] = sum(unlist(output[which(output$tag == tag_general$id[k]), "number"]))
  tag_general$daily_average[k] = round(tag_general$number_data[k]/tag_general$number_days[k])
}

datatable(tag_general, editable = F, extensions = 'Buttons', options = list(pageLength = 20, dom = 'Bfrtip'))
```

